# coding=utf-8
# Copyright 2021 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# python3
"""A module that removes promotional text from a field of a product.

This modules removes promotional text from a product field that matches patterns
found in the "promo_text_removal_optimizer_config_{lang}" config file.
It uses two methods to remove the text.
- Regular expression: Removes text that matches regular expressions in the
config.
- Exact match: Removes text that exactly matches text in the config.

It does not transform product data unless a config file for the given language
exists.
"""

import logging
import re
from typing import Any, Dict, Optional

import flask


class PromoTextRemover(object):
  """A class that removes text from a field of a product."""

  _language: Optional[str] = None
  _config: Optional[Dict[str, Any]] = None

  def __init__(self, language: str) -> None:
    """Initializes PromoTextRemover.

    Args:
      language: The configured language code.
    """
    super(PromoTextRemover, self).__init__()
    self._language = language
    self._config = flask.current_app.config.get('CONFIGS', {}).get(
        f'promo_text_removal_optimizer_config_{language}', {})

  def remove_text_from_field(self, product: Dict[str, Any],
                             field_key: str) -> None:
    """Removes text and regex patterns in the config file from a product field.

    Args:
      product: A product data.
      field_key: The target field key.
    """
    field_value = product.get(field_key)
    if not isinstance(field_value, str):
      logging.warning(
          'Failed to remove text because The value of %s is not a string',
          field_key)
      return

    field_value = self._remove_text_by_regex_patterns(field_value)
    field_value = self._remove_text_by_exact_match(field_value)
    field_value = _clean_up_value(field_value)
    product[field_key] = field_value

  def _remove_text_by_regex_patterns(self, target_text: str) -> str:
    """Removes regex patterns in the config file from target text.

    Args:
      target_text: The original text.

    Returns:
      A string generated by removing regex patterns from the target text.
    """
    regex_patterns = self._config.get('promotional_text_patterns_regex', [])
    for regex_pattern in regex_patterns:
      target_text = re.sub(regex_pattern, '', target_text, flags=re.I)
    target_text = ' '.join(target_text.split())
    return target_text

  def _remove_text_by_exact_match(self, target_text: str) -> str:
    """Removes text in the config file from target text.

    Args:
      target_text: The original text.

    Returns:
      A string generated by removing text from the target text.
    """
    text_list = self._config.get('promotional_text_patterns_exact_match', [])
    for text in text_list:
      target_text = target_text.replace(text, '')
    target_text = ' '.join(target_text.split())
    return target_text


def _clean_up_value(value: str) -> str:
  """Cleans up a field value."""
  return value.strip()
